### PR TITLE
os: doc change: 0OOO file modes to unambiguous modern 0oOOO style

### PR DESCRIPTION
**Pull request by mark-summerfield**
os: doc change: 0OOO file modes to unambiguous modern 0oOOO style

### CODE REVIEW

**Comment by mark-summerfield** [comment]
I clicked through and signed the CLA but don't know what to do next.

**Comment by ianlancetaylor** [comment]
The CLA bot thinks that you have not signed the CLA.  I checked the internal page, and you don't show up there.  It may help to look at https://go.dev/doc/contribute#cla.

**Comment by mark-summerfield** [comment]
When I click https://cla.developers.google.com/clas it shows I have a "Google Individual CLA".

**Comment by ianlancetaylor** [comment]
Make sure that the email address you use at cla.developers.google.com corresponds to an email address attached to your GitHub account.

**Pull request closed without merging**
