### PR TITLE
strings: add StripSlashes function for strings pkg

### PR DESCRIPTION
**Pull request by LockGit**
Add a StripSlashes function , Un-quotes a quoted string.

Description：
Returns a string with backslashes stripped off. (' becomes ' and so on.)
Double backslashes (\) are made into a single backslash ().

### CODE REVIEW

**Comment by LockGit** [comment]
@googlebot I signed it!

**Comment by LockGit** [comment]
> This PR (HEAD: [9ff9211](https://github.com/golang/go/commit/9ff9211b0bc8cc239e3d43eb36e832ccf7fb37af)) has been imported to Gerrit for code review.
> 
> Please visit https://go-review.googlesource.com/c/go/+/281372 to see it.
> 
> Tip: You can toggle comments from me using the `comments` slash command (e.g. `/comments off`)
> See the [Wiki page](https://golang.org/wiki/GerritBot) for more info

fmt.Println(StripSlashes(`\\\\1`))  // print   \\`
fmt.Println(strconv.Unquote(`\\\\1`)) print   invalid syntax

**Comment by agnivade** [comment]
@LockGit - Like Ian mentioned in the issue, I would suggest creating a proposal issue if you want your function to be added. Without that we cannot move forward.

**Comment by amnonbc** [comment]
How is this different from `strconv.Unquote()`

**Comment by mvdan** [comment]
Closing per Ian's comment on the CL.

**Pull request closed without merging**
