### PR TITLE
math: Pow(x,y) optimization for cases: constant integer `y`. 

### LINKED ISSUE #29456: math: math.Pow(x,y) optimization for cases: constant integer `y`.
math.Pow(x,y) optimization for cases: constant integer `y`. For example:
* `... math.Pow(length, 2)...`
* `... math.Pow(length, 3.0)...`

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes for `go 1.6`

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/konstantin/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/konstantin/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build700464290=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```go
package main

import (
        "math"
        "testing"
)

func BenchmarkMathPow(b *testing.B) {
        x := 42.0
        for i := 0; i < b.N; i++ {
                _ = math.Pow(x, 2.0)
        }
}

func BenchmarkInline(b *testing.B) {
        x := 42.0
        for i := 0; i < b.N; i++ {
                _ = x * x
        }
}
```

### What did you expect to see?
same or preliminary same performance between that 2 cases.

### What did you see instead?
run benchmark
```
> go test -bench=.
goos: linux
goarch: amd64
pkg: tmp
BenchmarkMathPow-4   	30000000	        49.6 ns/op
BenchmarkInline-4    	2000000000	         0.68 ns/op
PASS
ok  	tmp	2.992s
```
Different more 70 times.

### Note

Changing function `pow` in [math/pow.go](https://github.com/golang/go/blob/master/src/math/pow.go) is not enough for solving performance problem.
```go

func BenchmarkPowModify(b *testing.B) {
	x := 42.0
	for i := 0; i < b.N; i++ {
		_ = pow(x, 2.0)
	}
}

func pow(x, y float64) float64 {
	switch {
	case y == 0 || x == 1:
		return 1

// changes for cases with integer `y`.
	case float64(int8(y)) == y:
		if y < 0 {
			return 1.0 / pow(x, -y)
		}
		n := int(y)
		r := 1.0
		for i := 0; i < n; i++ {
			r *= x
		}
		return r

	case math.IsNaN(x) || math.IsNaN(y):
		return math.NaN()

... other like in file math/pow.go ....
```
result is better, but not `the best`:
```
BenchmarkMathPow-4     	30000000	        49.6 ns/op
BenchmarkPowModify-4   	200000000	         7.56 ns/op
BenchmarkInline-4      	2000000000	         0.69 ns/op
PASS
ok  	tmp	5.268s
```

Have we any optimization place for change AST from function expressions `math.Pow` with parameter `y` = 2 to expression `x*x`? (Like I understood `ssa` is not a right place).

### PR DESCRIPTION
**Pull request by Konstantin8105**
Fixes #29456

### CODE REVIEW

**Comment by Konstantin8105** [comment]
Benchstat:
```
name                   old time/op  new time/op  delta
/math.Pow(+128.000)-4  68.7ns ± 0%  67.3ns ± 0%   -2.04%  (p=0.000 n=10+6)
/math.Pow(+127.000)-4  60.0ns ± 0%  49.8ns ± 1%  -17.04%  (p=0.000 n=9+8)
/math.Pow(+126.000)-4  60.8ns ± 0%  47.9ns ± 0%  -21.20%  (p=0.000 n=10+8)
/math.Pow(+124.000)-4  61.4ns ± 0%  45.5ns ± 0%  -26.02%  (p=0.000 n=10+8)
/math.Pow(+100.000)-4  62.9ns ± 1%  35.7ns ± 0%  -43.24%  (p=0.000 n=9+7)
/math.Pow(+99.000)-4   61.8ns ± 0%  34.8ns ± 5%  -43.74%  (p=0.000 n=10+10)
/math.Pow(+19.000)-4   57.0ns ± 0%  25.8ns ± 2%  -54.72%  (p=0.000 n=10+9)
/math.Pow(+10.000)-4   54.9ns ± 0%  23.6ns ± 1%  -56.91%  (p=0.000 n=9+8)
/math.Pow(+5.000)-4    51.9ns ± 0%  21.2ns ± 0%  -59.04%  (p=0.000 n=10+9)
/math.Pow(+2.000)-4    50.1ns ± 0%  18.9ns ± 0%  -62.28%  (p=0.008 n=6+7)
/math.Pow(-2.000)-4    47.4ns ± 0%  16.8ns ± 0%  -64.47%  (p=0.000 n=10+10)
/math.Pow(-5.000)-4    49.1ns ± 0%  18.9ns ± 1%  -61.49%  (p=0.000 n=9+9)
/math.Pow(-10.000)-4   52.3ns ± 0%  21.6ns ± 0%  -58.66%  (p=0.000 n=10+8)
/math.Pow(-19.000)-4   54.2ns ± 0%  23.3ns ± 3%  -57.13%  (p=0.000 n=10+10)
/math.Pow(-99.000)-4   59.0ns ± 0%  33.2ns ± 1%  -43.74%  (p=0.000 n=9+8)
/math.Pow(-100.000)-4  60.2ns ± 0%  32.7ns ± 5%  -45.66%  (p=0.000 n=10+10)
/math.Pow(-124.000)-4  59.1ns ± 1%  43.6ns ± 0%  -26.29%  (p=0.000 n=10+8)
/math.Pow(-126.000)-4  59.0ns ± 0%  44.6ns ± 4%  -24.47%  (p=0.000 n=10+10)
/math.Pow(-127.000)-4  59.0ns ± 0%  46.5ns ± 1%  -21.19%  (p=0.000 n=10+9)
/math.Pow(-128.000)-4  65.9ns ± 0%  23.9ns ± 4%  -63.71%  (p=0.000 n=10+10)
/math.Pow(+128.100)-4   144ns ± 0%   143ns ± 1%   -0.83%  (p=0.000 n=7+10)
/math.Pow(+127.100)-4   139ns ± 0%   139ns ± 0%     ~     (p=0.137 n=8+10)
/math.Pow(+126.100)-4   139ns ± 0%   139ns ± 0%     ~     (all equal)
/math.Pow(+124.100)-4   139ns ± 0%   139ns ± 0%     ~     (all equal)
/math.Pow(+100.100)-4   139ns ± 1%   139ns ± 0%     ~     (p=0.173 n=10+9)
/math.Pow(+99.100)-4    139ns ± 0%   139ns ± 0%     ~     (all equal)
/math.Pow(+19.100)-4    134ns ± 1%   134ns ± 0%     ~     (p=0.337 n=10+10)
/math.Pow(+10.100)-4    130ns ± 1%   128ns ± 0%   -1.77%  (p=0.000 n=10+9)
/math.Pow(+5.100)-4     126ns ± 0%   128ns ± 1%   +1.35%  (p=0.000 n=9+10)
/math.Pow(+2.100)-4     123ns ± 0%   125ns ± 0%   +1.63%  (p=0.000 n=8+10)
/math.Pow(-1.900)-4     128ns ± 0%   130ns ± 0%   +1.95%  (p=0.000 n=8+10)
/math.Pow(-4.900)-4     128ns ± 1%   132ns ± 1%   +3.12%  (p=0.000 n=10+10)
/math.Pow(-9.900)-4     129ns ± 1%   132ns ± 1%   +2.32%  (p=0.000 n=10+10)
/math.Pow(-18.900)-4    133ns ± 0%   134ns ± 0%   +0.75%  (p=0.000 n=9+8)
/math.Pow(-98.900)-4    138ns ± 0%   139ns ± 1%   +0.87%  (p=0.000 n=9+10)
/math.Pow(-99.900)-4    138ns ± 1%   139ns ± 0%   +0.87%  (p=0.000 n=10+10)
/math.Pow(-123.900)-4   138ns ± 0%   142ns ± 1%   +2.54%  (p=0.000 n=8+10)
/math.Pow(-125.900)-4   138ns ± 0%   141ns ± 1%   +1.73%  (p=0.000 n=10+10)
/math.Pow(-126.900)-4   139ns ± 0%   141ns ± 0%   +1.68%  (p=0.012 n=8+3)
```

**Comment by pjebs** [comment]
Why'd the `case y == 1:` case get removed. It's still an optimization.

**Comment by Konstantin8105** [comment]
Dear @pjebs ,
The approach of that PR, optimization for integer value y = ~127..127. So, for case `y == 1` it is also work.

**Comment by pjebs** [comment]
I understand that, but having case `y==1` is still _technically_ faster (even if negligible)

**Comment by pjebs** [comment]
How can you beat this?:
```
case y == 1:	
		return x
```

**Comment by Konstantin8105** [comment]
Dear @pjebs ,
Yes, you are right.
On one hand, that PR slow down for `case y==1`(but I don't that in practice).
On another hand, that PR better for cases y == 2 ,y == 3 ... (I use it in practice).
So, prepare that PR in according to my practice of using function `math.Pow`.
Also, it is not a **best** way, the best way is `inline function with constant integer y`. For example I create a package for that https://github.com/Konstantin8105/pow with much more performance.
```
name          time/op
/math.Pow2-4   357ns ± 0%
/pow.E2-4     5.69ns ± 0%

/math.Pow3-4   359ns ± 1%
/pow.E3-4     8.86ns ± 1%
```

**Comment by pjebs** [comment]
You can keep `y == 1` case and your new case.

**Comment by Konstantin8105** [comment]
Dear @pjebs ,
Thank you for your point of view.
I will not return specific `case y == 1`, because I don't see the reason in practice point of view.

**Comment by mvdan** [comment]
Closing at the author's request.

**Pull request closed without merging**
