### PR TITLE
crypto/elliptic: generalize elliptic.Curve to allow A != -3

### PR DESCRIPTION
**Pull request by collinc97**
Fixes #26776

### CODE REVIEW

**Comment by collinc97** [comment]
I signed it!

**Comment by cag** [comment]
Confirm I'm ok with my commits being contributed to this project!

**Comment by Hirama** [comment]
When merge?

**Comment by shazow** [comment]
Do we need to override the `cla:no` label here somehow to get it reviewed?

**Comment by mvdan** [comment]
Looks like the proposal issue was declined. Leaving it up to @FiloSottile to decide what to do here, but I assume we can just close this PR.

**Comment by eliwjones** [comment]
I went ahead and pulled the code from the PR out and put a usable version here (tests and example included):

https://github.com/eliwjones/crypto

The main secp256k1 stuff I see out and about are wrappers of C code.

I have not seen a satisfactorily trustworthy native Go implementation.. so, if anyone knows of one, please post it here.

Linking to issue thread as well:
https://github.com/golang/go/issues/26776#issuecomment-535961254

**Comment by odeke-em** [comment]
The subject proposal/issue was closed in https://github.com/golang/go/issues/26776#issuecomment-497671740, thus closing this PR too. We appreciate your contributions to the Go project @collinc97, and look forward to interacting with you even more in the future. Thank you.

**Pull request closed without merging**
