### PR TITLE
doc: improve re.ReplaceAllString documentation related to Expand part

### PR DESCRIPTION
**Pull request by eduardbme**
Update documentation related to #40329 issue

### CODE REVIEW

**Comment by eduardbcom** [comment]
@googlebot I signed it!

**Comment by eduardbcom** [comment]
@googlebot I signed it!

**Comment by eduardbme** [comment]
Rebased to the current master, can we re-open and land it ?

**Comment by heschi** [comment]
GitHub says I can't: "The branch was force-pushed or recreated."

**Comment by eduardbme** [comment]
Okay, create a new one https://github.com/golang/go/pull/56507

**Pull request closed without merging**
