### PR TITLE
Check for slash in buildid, resolve #50809

### LINKED ISSUE #50809: cmd/buildid: crashes trying to write buildid in binary built by Go 1.5
### What version of Go are you using (`go version`)?
1.17.2 linux/amd64

<pre>
$ go version
1.17.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
linux

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
run `go tool buildid -w <filepath>` on a go 1.5 binary and the following error will occur:

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
main.main()
        /usr/local/go/src/cmd/buildid/buildid.go:56 +0x60d
```

The line:
https://github.com/golang/go/blob/cfad1ff84c45f99f6ceee17f76e2cbaf2ff8598b/src/cmd/buildid/buildid.go#L56

This is because in go 1.5 the contentID did not exist, so the slash seperator is not present, causing issues. The buildid tool doesn't consider legacy buildID/actionID/contentID layouts.

### What did you expect to see?
The buildID / contentID to be written

### What did you see instead?
crash

### PR DESCRIPTION
**Pull request by stevemk14ebr**
This resolves legacy go binaries crashing the buildid tool when the -w flag is specified. Resolves #50809

### CODE REVIEW

**Comment by stevemk14ebr** [comment]
I signed the CLA

**Comment by mvdan** [comment]
The CLA still seems to be failing. Are you sure you've signed it with the same email address you use in git? See https://go.dev/doc/contribute#cla.

**Comment by stevemk14ebr** [comment]
rewrote git history to use the same email as i signed cla with.

**Comment by mvdan** [comment]
You somehow ended up with tens of thousands of commits. Did you rewrite *all* the history?

**Comment by stevemk14ebr** [comment]
Yea I'm dumb that didn't work as I expected. I'm going to re-open with this with the correct author.

**Pull request closed without merging**
