### PR TITLE
strings: fix typo of the function explode

### PR DESCRIPTION
**Pull request by i6448038**
This commit will make the function explode’s  comment much more clear for the developers which are in the non-English speaking countries

### CODE REVIEW

**Comment by gitiafsaneh4** [comment]
> این تعهد باعث می شود عملکرد بسیار واضح تری برای توسعه دهندگان در کشورهای غیر انگلیسی زبان باشد

**Comment by gitiafsaneh4** [comment]
@gitiafsaneh4

**Comment by i6448038** [comment]
> @gitiafsaneh4

what did you mean？make fun of me ?
yes，China is one of the developing countries, but it is the biggest one.

**Comment by ianlancetaylor** [comment]
Please be respectful and charitable toward others, as discussed at the Go Community Code of Conduct (https://golang.org/conduct).  Thanks.

**Comment by i6448038** [comment]
> Please be respectful and charitable toward others, as discussed at the Go Community Code of Conduct (https://golang.org/conduct). Thanks.

yeah,I'm really sorry, Just this once

**Comment by i6448038** [comment]
> > این تعهد باعث می شود عملکرد بسیار واضح تری برای توسعه دهندگان در کشورهای غیر انگلیسی زبان باشد

@gitiafsaneh4 hi，body; what's meaning of this reply? I apologize for my recklessness. my translation software

**Comment by i6448038** [comment]
> > این تعهد باعث می شود عملکرد بسیار واضح تری برای توسعه دهندگان در کشورهای غیر انگلیسی زبان باشد

hi，body; what's meaning of this reply? I apologize for my recklessness. maybe there was something wrong with my translation software, what it translated was not very friendly, so i got angry for that. please forgive me

**Comment by mvdan** [comment]
Robert left a review on the CL but it didn't get a reply, so I'm closing this for now.

**Pull request closed without merging**
