### PR TITLE
bytes: deflake TestGrow by using testing.AllocsPerRun

### LINKED ISSUE #36695: bytes: TestGrow is flaky
[2020-01-19T20:36:10-df2999e/android-arm-corellium](https://build.golang.org/log/cf93614cc6aa6a6990f0d2966dfc320313dbd08e)

See previously #24647. The fix for that issue (in [CL 104235](https://golang.org/cl/104235)) only seems to have been applied to the `strings` package, not `bytes` — it probably just needs to be ported over.

(CC @dmitshur @toothrot @cagedmantis)

### PR DESCRIPTION
**Pull request by howjmay**
Fixes #36695

### CODE REVIEW

**Comment by HowJMay** [comment]
@googlebot I signed it!

**Comment by HowJMay** [comment]
Close this since I haven't finished it

**Comment by HowJMay** [comment]
Hi I just forced push a new commit, but I have problem to re-open this PR. Could you help me to reopen this PR?

**Comment by bcmills** [comment]
I'm not sure. Perhaps try the instructions at https://gist.github.com/robertpainsi/2c42c15f1ce6dab03a0675348edd4e2c?

**Comment by HowJMay** [comment]
@bcmills I googled it, and it seems to need permission to reopen it which I obviously don't have. 
Maybe I could open another PR for this branch?

**Comment by bcmills** [comment]
Try the first three steps (pushing the original hash) and then let me know — I'll see if I can reopen it from there.

**Comment by HowJMay** [comment]
Thank you @bcmills. I successfully reopen and push the new update.

**Pull request closed without merging**
