### PR TITLE
net/url: give a proper error message on invalid character in scheme

### LINKED ISSUE #29261: net/url: misleading error message when url has a leading space
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/stefanb/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/stefanb/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z2/3bdl__bs0xxd3kmf5c1pj0gm0000gn/T/go-build212726590=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go
package main

import (
	"net/http"
)

func main() {
	_, err := http.Get(" http://example.org")
	if err != nil {
		panic(err)
	}
}
```
https://play.golang.org/p/jkcYSD6ZRcO

### What did you expect to see?

Either 
* a generic error message of invalid URL or
* a detailed error of invalid URL scheme or
* a detailed error of leading space in URL

### What did you see instead?

A *misleading detailed* error message:
```
parse  http://example.org: first path segment in URL cannot contain colon
```

In #24246 the proposed solution was to trim the URLs before using them, but from the given error message it is very hard to see what the real problem is. 

I propose to either:
* adjust the error message to eg:
```
parse  http://example.org: URL scheme cannot contain spaces
```
or
* quote the problematic URL in the error message, so that it is more obvious even if the message itself remains misleading:
```
parse " http://example.org": first path segment in URL cannot contain colon
```
or
* ideally both adjust the error message + quote the URL:
```
parse " http://example.org": URL scheme cannot contain spaces
```

The `cannot contain spaces` in error message can be changed for `cannot contain whitespace` or even `contains invalid characters`, depending how the check is implemented.

Current implementation: https://github.com/golang/go/blob/b50210f5719c15cd512857e2e29e1de152155b35/src/net/url/url.go#L540-L562

### PR DESCRIPTION
**Pull request by cgopalan**
Fixes #29261

### CODE REVIEW

**Comment by cgopalan** [comment]
@agnivade I have made changes based on our discussion in the issue, but at the moment I have one failing test:
```
--- FAIL: TestFileServerEscapesNames (0.00s)
    fs_test.go:300: test "simple_name": Get: Get http://127.0.0.1:36757/0: failed to parse Location header "0/": parse 0/: URL scheme has invalid character
FAIL
FAIL	net/http	4.252s
```
Not sure why this is failing since the scheme seems to be fine. Would love to get some pointers on this.

**Comment by stefanb** [comment]
Please note that the negative tests are not actually testing the expected error message, just its mere presence.

**Comment by cgopalan** [comment]
@agnivade @stefanb in the failing test I mentioned above, it seems like the `0` in `http://127.0.0.1:36757/0` url is being parsed as a location header and as a result `0` is a valid beginning character for a url. Also there are tests that count on `/ . ? ;` being valid starting characters for a url so I had to include them.
Is this the right approach? Would like some guidance here.

**Comment by agnivade** [comment]
The code can do with some improvement. Your ` (c < 'A' || (c > 'Z' && c < 'a') || c > 'z') ` is repeated which I wanted to avoid. 

We don't typically discuss CLs in github. Gerrit is the place for that. Please feel free to ping Brad on the CL to get guidance.

**Pull request closed without merging**
