### PR TITLE
Update path.go

### PR DESCRIPTION
**Pull request by Tomator01**
Solve the problem of missing files while using package filepath.Walk .

This PR will be imported into Gerrit with the title and first
comment (this text) used to generate the subject and body of
the Gerrit change.

**Please ensure you adhere to every item in this list.**

More info can be found at https://github.com/golang/go/wiki/CommitMessage

+ The PR title is formatted as follows: `net/http: frob the quux before blarfing`
  + The package name goes before the colon
  + The part after the colon uses the verb tense + phrase that completes the blank in,
    "This change modifies Go to ___________"
  + Lowercase verb after the colon
  + No trailing period
  + Keep the title as short as possible. ideally under 76 characters or shorter
+ No Markdown
+ The first PR comment (this one) is wrapped at 76 characters, unless it's
  really needed (ASCII art, table, or long link)
+ If there is a corresponding issue, add either `Fixes #1234` or `Updates #1234`
  (the latter if this is not a complete fix) to this comment
+ If referring to a repo other than `golang/go` you can use the
  `owner/repo#issue_number` syntax: `Fixes golang/tools#1234`
+ We do not use Signed-off-by lines in Go. Please don't add them.
  Our Gerrit server & GitHub bots enforce CLA compliance instead.
+ Delete these instructions once you have read and applied them

### CODE REVIEW

**Comment by Tomator01** [comment]
image

In this path ,i use filepath.Walk to get all directory or file under "/home/pengpai/p2" ,but when  the variable skipobj is file not directory ,the return will lost some files.
 You can repet this issue by the following demo.

```
package main

import (
	"fmt"
	"io/fs"
	"os"
	//"github.com/path/filepath"
	"path/filepath"
)

func main() {
	dir := "/home/pengpai/p2"
	skipobj := "/home/pengpai/p2/test2.c"
	//skipobj := "/home/pengpai/p2/p1"
	var objlist []string
	filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if path == skipobj {
			return fs.SkipDir
		} else {
			objlist = append(objlist, path)
			return nil
		}

	})
	for _, obj := range objlist {
		fmt.Println(obj)
	}
}

```

When skipobj := "/home/pengpai/p2/test2.c" , the print :
image
Has lost  the test3.c and test.c .

When /skipobj := "/home/pengpai/p2/p1" ,the print:
image
is right.

This issue could lead to some file lost.

**Comment by ZekeLu** [comment]
I think you should change your walkFunc like this:

```diff
  		if path == skipobj {
- 			return fs.SkipDir
+ 			return nil
  		} else {
```

**Comment by Tomator01** [comment]
> I think you should change your walkFunc like this:
> 
> ```diff
>   		if path == skipobj {
> - 			return fs.SkipDir
> + 			if info.IsDir() {
> + 				return fs.SkipDir
> + 			}
> + 			return nil
>   		} else {
> ```

yes ,You are right ,but i think we can implement this in path package ,or why not？

**Comment by ZekeLu** [comment]
The behavior is documented: https://pkg.go.dev/path/filepath#WalkFunc

> The error result returned by the function controls how Walk continues. If the function returns the special value SkipDir, Walk skips the current directory (path if info.IsDir() is true, **otherwise path's parent directory**). Otherwise, if the function returns a non-nil error, Walk stops entirely and returns that error.

**Pull request closed without merging**
