### PR TITLE
syscall: implement arm_sync_file_range and SyncFileRange wrapper for ARM

### PR DESCRIPTION
**Pull request by agherzan**

### CODE REVIEW

**Comment by agherzan** [comment]
I signed it!

**Comment by agherzan** [comment]
I signed it!

**Comment by agners** [comment]
@agherzan do you plan to submit a pull request to https://github.com/golang/sys instead?

**Comment by agherzan** [comment]
@agners I'll resume this next week. I plan to do it wherever is needed. Is that supposed to get there?

**Comment by agners** [comment]
@agherzan ok, cool! Yes, see the gopherbot comment above.

**Pull request closed without merging**
