### PR TITLE
cmd/compile: resolve typo in (*.internal/types.Type).cmp

### LINKED ISSUE #40837: cmd/compile: bug due to typo in (*.internal/types.Type).cmp for TSSA
https://github.com/golang/go/blob/51ac0f0f4cb432204dee3d434335fd1e61ca8446/src/cmd/compile/internal/types/type.go#L1029
```
xname := t.Extra.(string)
```
should ACTUALLY BE:
```
xname := x.Extra.(string)
```

### PR DESCRIPTION
**Pull request by Celision**
fixes #40837

### CODE REVIEW

**Comment by PraxisProject** [comment]
@googlebot I signed it!

**Comment by ReewassSquared** [comment]
@googlebot I signed it!

**Comment by ReewassSquared** [comment]
@googlebotbI consent.

**Comment by ReewassSquared** [comment]
@googlebot I consent.

**Pull request closed without merging**
