### PR TITLE
crypto/md5: modify md5block_arm64.s optimization md5

### PR DESCRIPTION
**Pull request by kdjdbbfk**
This commit enhances the performance of the MD5 functionality on ARM64 architecture by optimizing the ROUND3 function in the `md5block_arm64.s` assembly file.

### Summary of Changes:
- Refactored the `ROUND3` macro to improve the computation order, introducing a new `ROUND3FIRST` macro to handle the initial calculation more efficiently.
- Optimized the XOR operations in the `ROUND3` macro to reduce unnecessary instructions and improve parallelism within the ARM64 architecture.

### Benchmark Results:
Performance testing was conducted on an ARM64 Linux machine using Go's benchmark tool. The benchmarks were run 10 times each to ensure statistical significance. The following results were observed:

| Benchmark             | Old Time (sec/op) | New Time (sec/op) | Change |
|-----------------------|-------------------|-------------------|--------|
| Hash8Bytes-8          | 175.0ns ± 2%      | 175.0ns ± 1%      | ~      |
| Hash1K-8              | 2.065µs ± 0%      | 2.060µs ± 0%      | -0.22% |
| Hash8K-8              | 15.31µs ± 0%      | 15.29µs ± 0%      | -0.11% |
| Hash8BytesUnaligned-8 | 174.0ns ± 1%      | 174.0ns ± 1%      | ~      |
| Hash1KUnaligned-8     | 2.067µs ± 0%      | 2.059µs ± 0%      | -0.41% |
| Hash8KUnaligned-8     | 15.44µs ± 0%      | 15.45µs ± 0%      | ~      |

    In terms of throughput:

| Benchmark             | Old Throughput (B/s) | New Throughput (B/s) | Change |
|-----------------------|----------------------|----------------------|--------|
| Hash8Bytes-8          | 43.58MiB/s ± 2%      | 43.69MiB/s ± 0%      | +0.24% |
| Hash1K-8              | 473.1MiB/s ± 0%      | 474.0MiB/s ± 0%      | +0.20% |
| Hash8K-8              | 510.4MiB/s ± 0%      | 511.0MiB/s ± 0%      | +0.11% |
| Hash8BytesUnaligned-8 | 43.80MiB/s ± 0%      | 43.82MiB/s ± 0%      | ~      |
| Hash1KUnaligned-8     | 472.5MiB/s ± 0%      | 474.3MiB/s ± 0%      | +0.38% |
| Hash8KUnaligned-8     | 506.1MiB/s ± 0%      | 505.8MiB/s ± 0%      | ~      |

### Larger File Performance:
When testing with large files (e.g., a 3GB file), the runtime was reduced from 8.65 seconds to 7.39 seconds, resulting in an approximate 9% reduction in execution time. This demonstrates a more significant performance gain when handling larger datasets.

Overall, these optimizations provide modest improvements for small input sizes and more noticeable performance benefits when processing larger files, especially in memory-intensive workloads like file hashing.

### CODE REVIEW

**Review by kalebers — APPROVED** [review]

**Comment by kdjdbbfk** [comment]
arm-old
goos: linux
goarch: arm64
pkg: crypto/md5
BenchmarkHash8Bytes-4            	 6902066	       174 ns/op	  46.03 MB/s
BenchmarkHash1K-4                	  582655	      2059 ns/op	 497.33 MB/s
BenchmarkHash8K-4                	   78613	     15262 ns/op	 536.76 MB/s
BenchmarkHash8BytesUnaligned-4   	 6906164	       174 ns/op	  46.01 MB/s
BenchmarkHash1KUnaligned-4       	  582601	      2058 ns/op	 497.49 MB/s
BenchmarkHash8KUnaligned-4       	   78133	     15357 ns/op	 533.45 MB/s
PASS
ok  	crypto/md5	7.916s

arm-new
goos: linux
goarch: arm64
pkg: crypto/md5
BenchmarkHash8Bytes-4            	 6905114	       174 ns/op	  46.07 MB/s
BenchmarkHash1K-4                	  582960	      2054 ns/op	 498.63 MB/s
BenchmarkHash8K-4                	   78751	     15251 ns/op	 537.15 MB/s
BenchmarkHash8BytesUnaligned-4   	 6911649	       174 ns/op	  46.06 MB/s
BenchmarkHash1KUnaligned-4       	  581740	      2053 ns/op	 498.72 MB/s
BenchmarkHash8KUnaligned-4       	   78244	     15332 ns/op	 534.32 MB/s
PASS
ok  	crypto/md5	7.908s

**Comment by kdjdbbfk** [comment]
goos: linux
goarch: arm64
pkg: crypto/md5
                      │  .\old.txt  │             .\new.txt              │
                      │   sec/op    │   sec/op     vs base               │
Hash8Bytes-8            175.0n ± 2%   175.0n ± 1%       ~ (p=0.070 n=10)
Hash1K-8                2.065µ ± 0%   2.060µ ± 0%  -0.22% (p=0.041 n=10)
Hash8K-8                15.31µ ± 0%   15.29µ ± 0%  -0.11% (p=0.050 n=10)
Hash8BytesUnaligned-8   174.0n ± 1%   174.0n ± 1%       ~ (p=0.721 n=10)
Hash1KUnaligned-8       2.067µ ± 0%   2.059µ ± 0%  -0.41% (p=0.001 n=10)
Hash8KUnaligned-8       15.44µ ± 0%   15.45µ ± 0%       ~ (p=0.912 n=10)
geomean                 1.770µ        1.768µ       -0.11%

                      │  .\old.txt   │              .\new.txt              │
                      │     B/s      │     B/s       vs base               │
Hash8Bytes-8            43.58Mi ± 2%   43.69Mi ± 0%  +0.24% (p=0.022 n=10)
Hash1K-8                473.1Mi ± 0%   474.0Mi ± 0%  +0.20% (p=0.037 n=10)
Hash8K-8                510.4Mi ± 0%   511.0Mi ± 0%  +0.11% (p=0.045 n=10)
Hash8BytesUnaligned-8   43.80Mi ± 0%   43.82Mi ± 0%       ~ (p=0.170 n=10)
Hash1KUnaligned-8       472.5Mi ± 0%   474.3Mi ± 0%  +0.38% (p=0.001 n=10)
Hash8KUnaligned-8       506.1Mi ± 0%   505.8Mi ± 0%       ~ (p=0.912 n=10)
geomean                 219.0Mi        219.3Mi       +0.15%

**Comment by kdjdbbfk** [comment]
This optimization is more pronounced when parsing large files, for example, when parsing 3G iso, the running time is reduced from 8.65s to 7.39s, which is about 9% less time

**Comment by kdjdbbfk** [comment]
Resubmitted the PR at: https://github.com/golang/go/pull/69302

**Pull request closed without merging**
