### PR TITLE
runtime: handle windows callback on non-go thread

### LINKED ISSUE #6751: runtime: windows callback on non-Go thread fails
<pre>This test

diff --git a/src/pkg/runtime/syscall_windows_test.go
b/src/pkg/runtime/syscall_windows_test.go
--- a/src/pkg/runtime/syscall_windows_test.go
+++ b/src/pkg/runtime/syscall_windows_test.go
@@ -240,5 +240,35 @@
 }
 
 func TestCallbackInAnotherThread(t *testing.T) {
-   // TODO: test a function which calls back in another thread: QueueUserAPC() or
CreateThread()
+   d := GetDLL(t, &quot;kernel32.dll&quot;)
+
+   f := func(p uintptr) uintptr {
+       return p
+   }
+   r, _, err := d.Proc(&quot;CreateThread&quot;).Call(0, 0, syscall.NewCallback(f), 123,
0, 0)
+   if r == 0 {
+       t.Fatalf(&quot;CreateThread failed: %v&quot;, err)
+   }
+   h := syscall.Handle(r)
+   defer syscall.CloseHandle(h)
+
+   switch s, err := syscall.WaitForSingleObject(h, 100); s {
+   case syscall.WAIT_OBJECT_0:
+       break
+   case syscall.WAIT_TIMEOUT:
+       t.Fatal(&quot;timeout waiting for thread to exit&quot;)
+   case syscall.WAIT_FAILED:
+       t.Fatalf(&quot;WaitForSingleObject failed: %v&quot;, err)
+   default:
+       t.Fatalf(&quot;WaitForSingleObject returns unexpected value %v&quot;, s)
+   }
+
+   var ec uint32
+   r, _, err = d.Proc(&quot;GetExitCodeThread&quot;).Call(uintptr(h),
uintptr(unsafe.Pointer(&amp;ec)))
+   if r == 0 {
+       t.Fatalf(&quot;GetExitCodeThread failed: %v&quot;, err)
+   }
+   if ec != 123 {
+       t.Fatalf(&quot;expected 123, but got %d&quot;, ec)
+   }
 }

fails with

C:\&gt;u:\test -test.v -test.run=Another
=== RUN TestCallbackInAnotherThread
--- FAIL: TestCallbackInAnotherThread (0.11 seconds)
        syscall_windows_test.go:259: timeout waiting for thread to exit
FAIL

hg id is 39c724dd7f25

Alex

PS: for after Go 1.2</pre>

### PR DESCRIPTION
**Pull request by billziss-gh**
Adds an extra M in mstartm0 and accounts for it in checkdead. This allows Windows callbacks created with syscall.NewCallback and syscall.NewCallbackCDecl to be called on a non-Go thread.

Fixes #6751

### CODE REVIEW

**Comment by billziss-gh** [comment]
I signed it!

**Comment by alexbrainman** [comment]
@bradfitz can you, please, check to see why Gerrit CL has not been created for this PR.

@billziss-gh I just submitted my change https://go-review.googlesource.com/c/go/+/114755 with the test. Could you, please, incorporate into your PR now?

Thank you.

Alex

**Comment by alexbrainman** [comment]
Lucky Andy. Thank you, Brad.

Alex

**Comment by billziss-gh** [comment]
@alexbrainman thanks for pushing this forward so fast. I am unclear what you want me to do though. Do you want me to pull your latest commit into my fork so that it is included in this PR?

**Comment by alexbrainman** [comment]
Yes, please include my change in your PR. And remove test line with t.Skip in it, so we can actually verify your change works. Thank you.

Alex

**Comment by billziss-gh** [comment]
Alex, will do. Thanks.

**Comment by alexbrainman** [comment]
Once your change is accepted and submitted it will go to the top of master as single commit. So feel free to rebase and sqwash your changes away.

Alex

**Comment by billziss-gh** [comment]
Understood. Thanks!

**Comment by billziss-gh** [comment]
Ok. Rebased, squashed and pushed -f. Somehow I didn't break anything (I think). Beginners luck!

**Comment by alexbrainman** [comment]
> Rebased, squashed and pushed -f

Cool. We will have to wait for Andy now to fix Gobot (that should push your change into our Gerrit). Then others can review and submit your code.

Thank you.

Alex

**Comment by andybons** [comment]
Lucky me indeed :) Thanks for your patience on this!

**Comment by alexbrainman** [comment]
> Lucky me indeed :) Thanks for your patience on this!

Thank you for fixing this. On your weekend.

Alex

**Comment by billziss-gh** [comment]
@alexbrainman thank you for your help with the process so far.

I am wondering if I have misunderstood the process and there is something I need to do at this point or we are simply waiting for all reviewers to respond.

**Comment by alexbrainman** [comment]
> I am wondering if I have misunderstood the process and there is something I need to do at this point or we are simply waiting for all reviewers to respond.

@billziss-gh @ianlancetaylor made 3 comments that you need to attend. He suggested you add comment here

https://go-review.googlesource.com/c/go/+/114802/1/src/runtime/proc.go#1296

and here

https://go-review.googlesource.com/c/go/+/114802/1/src/runtime/proc.go#1621

You should add comments and push new version (with the comments).

Ian also questioned correctness of your change here

https://go-review.googlesource.com/c/go/+/114802/1/src/runtime/proc.go#4220

and I see that you replied to his questions.

So maybe add comments as requested and push the change, or explain why you think comments are not needed.

Anyway https://go-review.googlesource.com/c/go/+/114802 has only patch set number 1, once you pushed another change, it will go to 2, and then 3 and so on. And to be sure, send PTAL to confirm once you want some action from reviewers.

And do not hesitate pinging us on this PR or on https://go-review.googlesource.com/c/go/+/114802 if you need some help.

Alex

**Comment by billziss-gh** [comment]
@alexbrainman sorry for the delay. I have added some comments as per the reviewer's request.

**Comment by billziss-gh** [comment]
Thank you. Per your instructions I have added the additional comment: "See issue #6751 for details."

**Comment by billziss-gh** [comment]
@alexbrainman @ianlancetaylor please take another look.

**Comment by alexbrainman** [comment]
> @alexbrainman @ianlancetaylor please take another look.

I just pinged Ian on https://go-review.googlesource.com/c/go/+/114802 in Gerrit. Hopefully he will get back to you when he can. You can always comment here or on Gerrit directly (you should be able to comment there and everything).

Alex

**Comment by billziss-gh** [comment]
Thank you @alexbrainman for your help and @ianlancetaylor for your review.

**Comment by alexbrainman** [comment]
Thank you @billziss-gh for fixing very old issue.

Alex

**Pull request closed without merging**
