### PR TITLE
time: allow formatting time as hour emoji

### PR DESCRIPTION
**Pull request by earboxer**

### CODE REVIEW

**Comment by Prajwal-Koirala** [comment]
$1000.00 bet.

This PR will never be approved.

**Comment by jalavosus** [comment]
...Just, why?

**Comment by Prajwal-Koirala** [comment]
> ...Just, why?

Thats what i said.

**Comment by earboxer** [comment]
I use it with my email client, [aerc](https://aerc-mail.org). It allows user-customizable date formats using go's time.format.

Representing time with emoji gives a rough time, but I don't care exactly what time the email came in. It's useful to me in that I can get a quick glance and tell how recent something is (especially in relation to another one).

It's also neat to save a little bit of screen width.
Compare "04-23 18:49" and "04-23🕡pm". This saves two characters of width (and can save more if you don't care about am/pm).

**Comment by Prajwal-Koirala** [comment]
@earboxer 
I can agree with you on this one, but this should not be a part of the standard package, if u want it than clone the package and then make a new repo for the time package with this added.

**Comment by batara666** [comment]
😂

**Comment by mvdan** [comment]
Closing older PRs that didn't sign the CLA. Feel free to reopen or re-send if you can sign it.

**Pull request closed without merging**
