### PR TITLE
Fixes #40926 for HTTP response on write error.

### LINKED ISSUE #40926: ResponseHeaderTimeout not honoured - response from server not visible to implementing part
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes it does

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxx\AppData\Local\go-build
set GOENV=C:\Users\xxx\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\xxx\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\xxx\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxx\AppData\Local\Temp\go-build406563982=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
The property  ResponseHeaderTimeout in http.Transport -is not honoured.
HTTP client performing POST/PUT requests is not informed about server response.

According to documentation if ResponseHeaderTimeout is set and fully writing the request happens implementation shall wait for specified time for response before sending error.

Configure ResponseHeaderTimeout
Prepare a POST/PUT request with body.
Try to send it to the server requiring authentication.
The server respond with authentication request and closed the client connection (to avoid sending huge file from not authenticated source)

```
	c := &http.Client{
		Transport: &http.Transport{
			ResponseHeaderTimeout: time.Second * 5,
		},
	}

	body := make([]byte, 1024*8)
	rand.Read(body)

	req, err := http.NewRequest("POST", fmt.Sprintf("http://%s/", ln.Addr().String()), bytes.NewReader(body))
	req.ContentLength = int64(len(body))
	if err != nil {
		t.Fatal(err)
	}
	resp, err := c.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	if resp == nil {
		t.Fatal("Response expected")
	}
	body, err = ioutil.ReadAll(resp.Body)
	resp.Body.Close()
	bodyText := string(body)
	if strings.Compare(IssuBody, bodyText) != 0 {
		t.Fatal("Response check failed")
	}
```

### What did you expect to see?

Correct response as server sends is before closing connection.
According to RFC that is right way of handling file uploads - RFC 2616:

> The server is refusing to process a request because the request entity is larger than the server is willing or able to process. The server MAY close the connection to prevent the client from continuing the request.

In case server is closing connection, client implementation will face write error, that is fine. But if before closing of the connection response is being send it shall be visible to the client.

### What did you see instead?
Error from http.Transport on write of request body should not be returned if within time specified in http.Transport property ResponseHeaderTimeout a valid response is received.

### PR DESCRIPTION
**Pull request by 74qb**
Fixed behaviour of ResponseHeaderTimeout in http.Transport - even in case property was set it was not honoured.
According to documentation if ResponseHeaderTimeout is set and fully writing the request happens implementation shall wait for specified time for response before sending error.

Steps to reproduce:

    Prepare a POST/PUT request with body.
    Try to send it to the server requiring authentication.
    The server respond with authentication request and closed the client connection (to avoid sending huge file from not authenticated source)

Result the method RoundTrip returned error only without response.
Expectation response will be returned if received within specified time span.

### CODE REVIEW

**Comment by qba667** [comment]
@googlebot I consent.

**Comment by qba667** [comment]
@tz70s @bcmills @zhangfannie @cuonglm can you please consent? I just rebased my code to resolve conflicts so it contains your commits.

**Comment by zhangfannie** [comment]
@googlebot I consent.

**Comment by tz70s** [comment]
@googlebot I consent.

**Comment by mvdan** [comment]
If you want to go ahead with this change, I would suggest to squash and rebase your commits into a single one authored just by yourself. That should make the CLA bot happy.

**Pull request closed without merging**
