### PR TITLE
mime: keep going parsing after trailing semicolon

### LINKED ISSUE #46323: mime: ParseMediaType drops value with trailing semicolon
### What version of Go are you using (`go version`)?

<pre>
// up to go current playground version
package main

import (
	"fmt"
	"runtime"
)

func main() {
	fmt.Println(runtime.Version())
}
</pre>
go1.16.4

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
go playground env
 
### What did you do?

https://play.golang.org/p/kIcw1CfXcUq

```
package main

import (
	"fmt"
	"mime"
)

func main() {
	// example from rfc2231 (p.3)

	const (
		contentTypeSucc = `message/external-body; access-type=URL;
         URL*0="ftp://";
         URL*1="cs.utk.edu/pub/moore/bulk-mailer/bulk-mailer.tar"`
		contentTypeFail = `message/external-body; access-type=URL;
         URL*0="ftp://";
         URL*1="cs.utk.edu/pub/moore/bulk-mailer/bulk-mailer.tar";`	// <-- !!!
	)
	
	r1, p1, err1 := mime.ParseMediaType(contentTypeSucc)
	r2, p2, err2 := mime.ParseMediaType(contentTypeFail)
	
	fmt.Println(r1, p1, err1)
	fmt.Println(r2, p2, err2)
}
```

### What did you expect to see?
```
message/external-body map[access-type:URL url:ftp://cs.utk.edu/pub/moore/bulk-mailer/bulk-mailer.tar] <nil>
message/external-body map[access-type:URL url:ftp://cs.utk.edu/pub/moore/bulk-mailer/bulk-mailer.tar] <nil>
```

### What did you see instead?
```
message/external-body map[access-type:URL url:ftp://cs.utk.edu/pub/moore/bulk-mailer/bulk-mailer.tar] <nil>
message/external-body map[access-type:URL] <nil>
```

### Analysis
this https://github.com/golang/go/blob/go1.16.4/src/mime/mediatype.go#L170 (https://golang.org/src/mime/mediatype.go?#L170) should be `break` instead of `return`

### Question
Should I next time push fix commit instead of writing issue if I  found both a bug and a fix to it at once?

### PR DESCRIPTION
**Pull request by Illirgway**
Fixes #46323

### CODE REVIEW

**Comment by Illirgway** [comment]
How can i write some comment/answer in gerrit from browser?
I suddenly can't find any input or button to do that.

**Comment by ianlancetaylor** [comment]
You have to sign into Gerrit to respond to comments there.

**Comment by Illirgway** [comment]
I sign into Gerrit by my email, but I can't found any reply/comment button/input

**Comment by ianlancetaylor** [comment]
When I go to https://golang.org/cl/332509 I see a blue "Reply" button in the middle, near the top, above the description of the change.  What do you see?

**Comment by Illirgway** [comment]
[I see this](https://snipboard.io/KpSrxV.jpg)

**Comment by ianlancetaylor** [comment]
That's odd.  You're right, of course: there is no Reply button.  Here are examples of what the page should look like for a signed in user: https://gerrit-review.googlesource.com/Documentation/user-review-ui.html .  What browser and OS are you using?

It may be appropriate to raise this as an issue with Gerrit.  See https://www.gerritcodereview.com/issues.html.  Assuming that web page works for you....

Sorry for the difficulties.

**Comment by Illirgway** [comment]
I have 2 js errors in debug console

_gr-app.js:28535:1_
`ReferenceError: ResizeObserver is not defined
Стек-трейс:
connectedCallback@https://cdn.googlesource.com/polygerrit_ui/870.0/elements/gr-app.js:23643:49
n.connectedCallback@https://cdn.googlesource.com/polygerrit_ui/870.0/bower_components/webcomponentsjs/webcomponents-lite.js:258:112
Pf@https://cdn.googlesource.com/polygerrit_ui/870.0/bower_components/webcomponentsjs/webcomponents-lite.js:253:349
eg/Node.prototype.insertBefore@https://cdn.googlesource.com/polygerrit_ui/870.0/bower_components/webcomponentsjs/webcomponents-lite.js:279:18
__createAndInsertInstance@https://cdn.googlesource.com/polygerrit_ui/870.0/elements/gr-app.js:2328:329
__ensureInstance@https://cdn.googlesource.com/polygerrit_ui/870.0/elements/gr-app.js:2321:392
__render@https://cdn.googlesource.com/polygerrit_ui/870.0/elements/gr-app.js:2321:554
__debounceRender/this.__renderDebouncer<@https://cdn.googlesource.com/polygerrit_ui/870.0/elements/gr-app.js:2318:192
setConfig/this._timer<@https://cdn.googlesource.com/polygerrit_ui/870.0/elements/gr-app.js:2137:929
microtaskFlush$$module$third_party$javascript$polymer$v2$polymer$lib$utils$async@https://cdn.googlesource.com/polygerrit_ui/870.0/elements/gr-app.js:1920:411`

  _gr-app.js:23651:328_
`TypeError: e.composedPath is not a function[Подробнее]  gr-app.js:23651:328`

And can't open (white screen) gerrit's 'add issue' page

**Comment by ianlancetaylor** [comment]
I'm sorry, I have no suggestions.  It does seem to work for most people.

What browser and OS are you using?

**Comment by Illirgway** [comment]
FF 56 x64

I don't yet update it to Quatum because of plugins

**Pull request closed without merging**
