### PR TITLE
cmd/go/internal/get: fix go get for Azure DevOps Git repos

### PR DESCRIPTION
**Pull request by MrWako**
The existing URL parsing logic is incompatible with the format of Azure 
DevOps Git repos. This revision enables the go get command to work with
Azure DevOps repos under the following assumptions:
* Only Git repos are supported, not TFVC. TFVC is not available for 
  public repos anyway.
* If the Git repo name has a .git extension in Azure DevOps then the
  extension needs to be added in the import path, 
  e.g. import "dev.azure.com/organization/project/package.git"
* The _git part of the Azure DevOps URL is removed when the package is
  cloned to the GOPATH

Fixes #28236

### CODE REVIEW

**Comment by bketelsen** [comment]
@FiloSottile This would be awesome in Go 1.12 👍

**Comment by FiloSottile** [comment]
Tentatively milestoned the issue for 1.12 (pending decision). 👍 

(A reminder to comment on issues and not PRs 😉)

**Comment by crsdrw** [comment]
I am OK with my commit being used in this pull request.

**Comment by mvdan** [comment]
The issue this PR is attempting to fix has been fixed for a while, as far as I can tell. This PR is also stuck with CLA issues and git conflicts, so it doesn't appear like it's going to advance. As such, I'm closing this for now.

If the issue should indeed be reopened, please comment there.

**Pull request closed without merging**
