### PR TITLE
runtime/type: change fieldalign to use mixedCaps

### PR DESCRIPTION
**Pull request by two**
all spelling in source code is "fieldAlign", except this place, so change "fieldalign" to use mixedCaps

### CODE REVIEW

**Comment by two** [comment]
@googlebot I fixed it..

**Comment by andybons** [comment]
@two the bot doesn’t think anything has changed.

Also:

+ You should delete the body text of the PR. It’s still the template.
+ Rename the title to be `runtime/type: change fieldalign to use mixedCaps`

**Comment by two** [comment]
> @two the bot doesn’t think anything has changed.
> 
> Also:
> 
> * You should delete the body text of the PR. It’s still the template.
> * Rename the title to be `runtime/type: change fieldalign to use mixedCaps`

TKS

**Comment by two** [comment]
> We found a Contributor License Agreement for you (the sender of this pull request), but were unable to find agreements for all the commit author(s) or Co-authors. If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA ([login here](https://cla.developers.google.com/) to double check)? If these were authored by someone else, then they will need to sign a CLA as well, and confirm that they're okay with these being contributed to Google.
> In order to pass this check, please resolve this problem and then comment `@googlebot I fixed it.`. If the bot doesn't comment, it means it doesn't think anything has changed.
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fgolang%2Fgo%2Fpull%2F34158) for more info**.

@googlebot I fixed it..

**Comment by two** [comment]
@googlebot I fixed it..

**Comment by andybons** [comment]
@two the commit author email (t..@cp1...du.com) has not signed a CLA. You must do so before you can proceed. Look at the "Logged in as ____" in the upper right of [this page](https://cla.developers.google.com/). If that email does not match the email of the commit, it won't think you've signed a CLA.

**Comment by two** [comment]
> @two the commit author email (t..@cp1...du.com) has not signed a CLA. You must do so before you can proceed. Look at the "Logged in as ____" in the upper right of [this page](https://cla.developers.google.com/). If that email does not match the email of the commit, it won't think you've signed a CLA.

sorry for used wrong email address , I have another PR #34441

**Pull request closed without merging**
