### PR TITLE
text/template: fix lint typo in VariableNode doc

### PR DESCRIPTION
**Pull request by imacks**

### CODE REVIEW

**Comment by odeke-em** [comment]
Thank you for this PR @imacks, and welcome to the Go project!

In order for your change to be reviewed, and accepted, you need to sign the Google Corporate License Agreement as referenced in https://github.com/golang/go/pull/39622#issuecomment-645057857. When ready please comment back, and then it’ll mirror to Gerrit.

**Comment by imacks** [comment]
@googlebot I signed it!

**Comment by imacks** [comment]
CLA signed i think :) @odeke-em

**Comment by odeke-em** [comment]
Awesome, it has now been mirrored on Gerrit, and will be reviewed and merged. Thank you for this contribution, and keep finding more, see you around!

**Pull request closed without merging**
