### PR TITLE
flag: increase coverage on TestSetOutput

### PR DESCRIPTION
**Pull request by cornfeedhobo**

### CODE REVIEW

**Comment by cornfeedhobo** [comment]
I didn't realize I needed a gmail account to contribute

**Comment by mvdan** [comment]
Closing older PRs that didn't sign the CLA. Feel free to reopen or re-send if you can sign it.

**Comment by cornfeedhobo** [comment]
@mvdan any way you could raise the Gmail requirement issue?

**Comment by mvdan** [comment]
I don't think you need a gmail account, you just need a Google account. I don't use gmail at all, for example.

**Comment by cornfeedhobo** [comment]
@mvdan I think you should revisit the process in a browser you aren't logged into already. It 100% requires you have to login with a google account.

**Comment by cornfeedhobo** [comment]
Yeah don't re-open it. I left it open in the hopes someone, like you 😉, would post the patch, but I guess I can submit it to the mailing list to find someone.

**Pull request closed without merging**
